config/routes.rb
Rails.application.routes.draw do
  root 'search#index'

  resources :search, only: [:index, :show], path: 'photo'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:search] || params[:page]
      query = Search.search_by(query: params[:search][:query], page: params[:page])
      respond_to do |format|
        format.html do
          @photos = JSON.parse(query.to_json, object_class: OpenStruct)
          @photos.search = params[:search][:query] # save search query throw pagination
        end
        format.json { render json: query }
      end
    else
      @photos = {}
    end
  end

  def show
    query = Search.show_image(id: params[:id])
    respond_to do |format|
      format.html { @photo = JSON.parse(query.to_json, object_class: OpenStruct) }
      format.json { render json: query }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content=('text/html; charset=UTF-8') http-equiv='Content-Type'/>
    <title>ImageSearcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/_big_photos.html.slim
- @photos.results.each do |photo|
  .image-block
    = link_to(image_tag(photo.urls.regular), search_path(photo.id))

app/views/search/_small_photos.html.slim
.image-block-flex
  - @photos.results.each do |photo|
    .image-items-flex
      = link_to(image_tag(photo.urls.small), search_path(photo.id))

app/views/search/index.html.slim
.index
  .search-container
    .search-block
      .search
        = simple_form_for :search,
          url: { action: 'index' },
          wrapper: :inline_form,
          html: { class: 'form-inline' },
          method: :get do |f|
          = f.input :query
          = f.button :submit, 'Search photos', id: 'search_submit'
  - if @photos.present? && @photos.results.present?
    .image-container
      ul.nav.nav-tabs
        li.active
          a data-toggle="tab" href="#big_photos"
            span.glyphicon.glyphicon-th-large
        li
          a data-toggle="tab" href="#small_photos"
            span.glyphicon.glyphicon-menu-hamburger
      .tab-content
        #big_photos.tab-pane.fade.in.active
          = render "search/small_photos"
        #small_photos.tab-pane.fade
          = render "search/big_photos"
      .pagination-block
        ul.pagination
          - (1..@photos.total_pages).each do |page|
            li
              = link_to search_index_path(search: {query: @photos.search}, page: page)
                = page

app/views/search/show.html.slim
.image-container-show
  .image-block
    = image_tag(@photo.urls.regular)
  .image-info
    .info
      span.glyphicon.glyphicon-resize-full
      = @photo.width
      '  x
      = @photo.height
      | pixels
    .user
      = image_tag(@photo.user.profile_image.small)
      =  @photo.user.name
    .download
      =link_to('Download', "#{@photo.links.download}?force=true", class: 'btn btn-default' )